/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/18/24, 12:31 PM' 
 * Generated by 'Ravi Teja P' 
 * Generated on server 'RAVITEJA.HSD1.CT.COMCAST.NET.' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:51452/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257BC127432C-2C7E-4020-B739-FB2D6C19230C%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.ELECTRICITY1 out=Work.preProcessedData;
	by DateTime;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecast forecastonly) ) out=work.out;
	identify var=Consumption crosscorr=(Nuclear Wind Hydroelectric 'Oil and Gas'n 
		Coal Solar Biomass) outcov=work.outcov;
	estimate p=(1 2 3 4) 
	input=(2 $ Nuclear 4 $ Wind 1 $ Hydroelectric 'Oil and Gas'n Coal Solar Biomass) 
	method=ML outest=work.outest outstat=work.outstat 
		outmodel=work.outmodel;
	forecast lead=12 back=12 alpha=0.05 id=DateTime interval=week printall;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;