/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/17/24, 5:10 PM' 
 * Generated by 'prathyusha kalepalli' 
 * Generated on server 'LAPTOP-JU0MCQ45.HSD1.CT.COMCAST.NET.' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:50891/main?locale=en_IN&zone=GMT-05%253A00&sutoken=%257B1E10723C-CBD7-45AE-AAE2-07CEDC01C87F%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=WORK.IMPORT out=Work.preProcessedData;
	by DateTime;
run;

proc timeseries data=Work.preProcessedData seasonality=52 plots=(series cycles 
		corr decomp tc tcc sc ic);
	id DateTime interval=week;
	var Consumption / accumulate=average transform=none dif=0 sdif=0;
	decomp tc trendcycle seasonal irregular / mode=multoradd;
run;

/* Unit root test analysis */
proc arima data=Work.preProcessedData plots=none;
	ods select StationarityTests;
	identify var=Consumption stationarity=(adf=2);
	run;
quit;

proc delete data=Work.preProcessedData;
run;