/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/17/24, 4:26 PM' 
 * Generated by 'prathyusha kalepalli' 
 * Generated on server 'LAPTOP-JU0MCQ45.HSD1.CT.COMCAST.NET.' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36' 
 * Generated on web client 'http://localhost:50891/main?locale=en_IN&zone=GMT-05%253A00&sutoken=%257B1E10723C-CBD7-45AE-AAE2-07CEDC01C87F%257D&openfile=D%253A%255CPrathyusha%2520Kalepalli%255CDesktop%255CForecasting-datasets-OPIM5671%255CData%255CModeling%2520and%2520Forecasting%2520Arima.ctk' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.ELECTRICITY1 out=Work.preProcessedData;
	by DateTime;
run;

proc arima data=Work.preProcessedData plots
    (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecastonly));
	identify var=Hydroelectric;
	estimate p=(1 2 3 4 5 6) q=(1 2)method=ML;
	identify var=Consumption crosscorr=(Hydroelectric);
	estimate input=(Hydroelectric) method=ML;
	forecast lead=12 back=0 alpha=0.05 id=DateTime interval=week;
	outlier;
	run;
quit;

proc delete data=Work.preProcessedData;
run;